### ISSUE TITLE
Mejorar la estructura de la conexión a la base de datos

### ISSUE THREAD

**Issue by diegode-tsx** [DiegoG28/nova-up-api#1]
Actualmente la conexión a la base de datos se realiza dentro del módulo principal "app". Es conveniente separar responsabilidades y crear un módulo que se encargue únicamente de la conexión a la base de datos.

**Comment by RomanshkVolkov** [comment]
Pendiente de revisión ffc476515bb7f83478de4ef88c5aee4b62221a28

**Comment by itsdiegode** [comment]
Piola
